const express = require('express');
const router = express.Router();
const { EventFundRegister ,getEventFund,getEventFundBtStudentId,updateEventFundStatus} = require('../controllers/EventFundController.js');
const IsWarden=require("../utils/IsWarden.js");
const IsStudent = require('../utils/IsStudent.js');
router.post('/EventFund',IsStudent,EventFundRegister);
router.get('/EventFund/get',IsWarden, getEventFund);
router.post("/EventFund/student/get",IsStudent ,getEventFundBtStudentId);
router.put("/EventFund/admin/update",IsWarden, updateEventFundStatus);
module.exports = router;